### ISSUE TITLE
Include Media store, items and folders in workflow permissions

### ISSUE THREAD

**Issue by HistoricEnglandDigitalTeam** [nathanwoulfe/Plumber#106]
It would be really useful if workflow permissions could be set for media items, as well as Content 
 / document types.  Whilst here are other packages that handle permission for 'members', there are none that do this for 'users'.

At present, any Umbraco editor can delete / move/copy a media item, as the user settings only apply to 'content'. That can have unfortunate, accidental, consequences. Nor is there any editor history for media.

Not sure if this is an enhancement for Plumber, or for Umbraco core....

regards Fiona

**Comment by nathanwoulfe** [comment]
Probably a bit of both - some of this Plumber could manage, some would be Umbraco core stuff. There's currently no permissions for media in core, but Plumber might just work as is, I haven't tried it. Would need a different permissions model since media doesn't have the save+publish concept at all, so might be something I look at for v8 since that requires a refactoring of a lot of the project.

Not sure that it would ever work for doc types - best bet there is to block all users from the settings section on prod, since making changes will likely break things.

For media, the other option is to hide the context menu items for users so they can still browse and upload, but not perform other actions. Moving and copying shouldn't break anything since media aren't referenced by their location in the media section (and the folders are virtual), but obviously deleting would break stuff.
