### ISSUE TITLE
As a member of an approver group, I can self-approve my own requests?

### ISSUE THREAD

**Issue by alanwthom** [nathanwoulfe/Plumber#120]
This is potentially more of a question (which may lead to a feature request). I've just installed Plumber (v1.11.1) on a local installation and have been getting to grips with the workflows, configuration, steps, etc. 

I've carried out the following:
1. Create an approval group which contains two editors (of which you are one)
2. Edit a content node and request approval
3. Navigate to workflow dashboard and content node appears as a task requiring my approval
4. Approve content node which you've just edited
5. Content node is published 

My expectation was that I would not be able to approve my own changes (a la peer review), but that the other member of the approval group would have to approve these before they could be published, however I was able to approve and publish my own changes.

Have I missed something in the configuration when setting this up (or configured things incorrectly), or is this expected behaviour? (Secondary question if this is expected behaviour, would you be open to a feature request/PR to add a configuration setting to prevent this?)

Thanks

**Comment by nathanwoulfe** [comment]
Hi @alanwthom, that's the expected behaviour - there is an option to set the workflow type, where you can control how the change author is included in subsequent workflow stages:

- implicit: workflows steps where the change author is a member of the approving group are automatically approved
- explicit: all workflow steps require approval, regardless of group membership

My thinking was that it would be uncommon to have a workflow configured for a piece of content where potential editors of that content would then be included in approval groups for that workflow. In the case that they are members, then by virtue of being part of that group, the assumption is that they would approve their own changes.

That's all good, for those scenarios. It doesn't mean though that those are the only scenarios - I can see that there would be value in a third option, where the original editor is excluded from the workflow process. I'm happy to work up a solution (I'm currently finishing the v8 release, so would need to do it there and backport it to v7)
