### ISSUE TITLE
What version of plumber uses .net 4.5.2? if at all?

### ISSUE THREAD

**Issue by EM-Benji** [nathanwoulfe/Plumber#131]
More of a question than and issue or bug

**Is your feature request related to a problem? Please describe.**
Website is built in .net 4.5.2, workflow uses .net 4.6. which hasn't been an issue until we wanted to subscribe to an event and needed to reference workflow and now the project wont build, it isn't finding the references yet they exist and intellisense works.

updating the website to 4.6 is a solutions but potentially requires a lot of retesting etc.

**Describe the solution you'd like**
plumber version in .net 4.5.2, if can be built or an older version number that uses it 

Any ideas would be great.

**Comment by nathanwoulfe** [comment]
I've never built against 4.5, only 4.6+ because that would have been the dev environment on my machine when I started. I don't intend rebuilding against 4.5, since I don't know what changes would be required - might be a minor job, might be a big one. Don't really have time, given V8 support and Plumber2 is my priority. 

That said, the source is all available if you want to download and try compiling it yourself 😉

**Comment by EM-Benji** [comment]
It was a bit of a hell mary anyway, but thanks for the reply.
