### ISSUE TITLE
Refactor to remove requirement for setting root node group - default approver in settings should be enough.

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#40]
I setting all but Plumber give this message:

![image](https://user-images.githubusercontent.com/661517/39564172-6e157840-4eb3-11e8-9669-9818fcf4a0fc.png)

Why?

**Comment by nathanwoulfe** [comment]
Do you have a workflow configured on the homepage node or homepage document type?

**Comment by biapar** [comment]
Hi,
no.
The workflow must be execute only on document type"Richieste" under node "Richieste".

![image](https://user-images.githubusercontent.com/661517/39578357-4247c016-4ee4-11e8-9560-f5b04feb00fa.png)

**Comment by nathanwoulfe** [comment]
By design, the package expects a workflow to be configured on the root node, which isn't necessarily the best way to set it up - I'll need to have a look at how to modify things to have it work correctly without a group assigned on the root node.

To make it work for now, you'd need to set a group on the root, then exclude the children (which won't work on 0.7.8 as the excluded node picker is only permitting a single selection).
