### ISSUE TITLE
following errors occurred while attempting to load the app

### ISSUE THREAD

**Issue by pyajamanam** [nathanwoulfe/Plumber#72]
**Describe the bug** Umrbaco version 7.10.4
The following errors occurred while attempting to load the app.
- The OwinStartupAttribute.FriendlyName value 'UmbracoDefaultOwinStartup' does not match the given value 'WorkflowOwinStartup' in Assembly 'umbraco, Version=1.0.6684.15731, Culture=neutral, PublicKeyToken=null'.
- The given type or method 'WorkflowOwinStartup' was not found. Try specifying the Assembly.
To disable OWIN startup discovery, add the appSetting owin:AutomaticAppStartup with a value of "false" in your web.config.
To specify the OWIN startup Assembly, Class, or Method, add the appSetting owin:AppStartup with the fully qualified startup class or configuration method name in your web.config.

**To Reproduce**
1. install plumber 0.9.3 after installing plumber 0.9.2 and reinstall 0.9.3
2. it will install and by the time its shows restart it will struck and when we refresh manually it wil go to internal server error.
when i change integratedpiplinemode to un comment and it will start working.
3. when i am configuring workflow  and start approving with sequence, by clicking aprrove changes button shows loadinng but after refersh it willl come workflowdetail. 
4. console errors;
![image](https://user-images.githubusercontent.com/33079424/45204341-84f39b80-b29c-11e8-92ad-727616eb67ec.png)

**Comment by nathanwoulfe** [comment]
Owin issue looks like config - how have you set it up?

Button text change is by design - when a node is in a workflow and the current user can't action it, the button default is the workflow overview. 

The js error looks like old files - if you've installed the package you shouldn't have the individual files in your solution, just the compiled, minified, concatenated output from the build. Have you installed the source into the same solution previously?

These are really separate issues and should have been logged as such. Makes it pretty difficult to keep track of legitimate bugs when multiple issues are raised in a single task.
